server:
  port: 8080

#eureka客户端配置
eureka:
  client:  #将客户端注册到eureka的服务列表
    service-url:
      #单机版 defaultZone: http://localhost:8888/eureka
      #集群版配置注册服务器地址
      defaultZone: http://eureka2.com:8889/eureka/,http://eureka1.com:8888/eureka/,http://eureka3.com:8890/eureka/