server:
  port: 8889
eureka:
  instance:
    hostname: eureka2.com  #euraka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，职责就是维护服务，并不需要去检索服务
    service-url:
      #设置与Eureka交互的地址查询服务和注册服务
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置 需要配置域名映射
      defaultZone: http://eureka1.com:8888/eureka/,http://eureka3.com:8890/eureka/

